import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="bg-gray-100 m-1 p-1 rounded-md">
      <div>
        <nav className="flex items-center justify-between p-1">
          <div className="bg-gray-50 p-1 rounded-md">
            <Link href="/">Home</Link>
          </div>
          <div className="bg-gray-50 p-1 rounded-md">
            <Link href="/cv">CV</Link>
          </div>
        </nav>
      </div>
    </header>
  );
}

function Footer() {
  return <footer className="bg-gray-100 m-1 p-1 rounded-md">Footer</footer>;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
