import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header
      className="
        m-1 p-1 rounded-md
        bg-gray-100
        dark:bg-gray-800
      "
    >
      <nav className="flex items-center justify-between p-1">
        <div
          className="
            bg-gray-50 p-1 rounded-md
            dark:bg-gray-700
          "
        >
          <Link href="/">Home</Link>
        </div>
        <div
          className="
            bg-gray-50 p-1 rounded-md
            dark:bg-gray-700
          "
        >
          <Link href="/cv">CV</Link>
        </div>
      </nav>
    </header>
  );
}

function Footer() {
  return (
    <footer
      className="
        m-1 p-1 rounded-md
        bg-gray-100
        dark:bg-gray-800
      "
    >
      Footer
    </footer>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col
          bg-gray-50 text-gray-900
          dark:bg-gray-900 dark:text-gray-100`}
      >
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
